on: workflow_dispatch

name: Aikido Scan Dockerized
jobs:
  aikido-local-scan-repo:
    runs-on: ubuntu-latest
    container:
      image: aikidosecurity/local-scanner:latest
    steps: 
      - uses: actions/checkout@v4 
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          path: ${{ github.repository }}
      - name: Run scan
        run: aikido-local-scanner scan ${{ github.repository }} --repositoryname ${GITHUB_REPOSITORY#*/} --branchname --main --apikey AIK_CI_J7eearnk2Lojjtp6jTfvne8BKbg2qcm98nDTg4tSRtSOdNe9wnSSK3lf59D5FUlF --debug
