on: workflow_dispatch

name: Scan within Alpine
jobs:
  scan-repo:
    runs-on: ubuntu-latest
    container:
      image: docker:stable
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          path: demo-app
      - name: Install Aikido selfscanner
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'skeymeulen/releasetetest'
          version: 'tags/v1'
          file: 'aikidoselfscanner_linux_X86_64.zip'
      - name: unzip
        run: unzip aikidoselfscanner_linux_X86_64.zip
      - name: test
        run: chmod +x aikido-local-scanner
      - name: ls
        run: ls
      - name: Run scan
        run: aikido-local-scanner image-scan node:16 --apikey AIK_CI_bLLAgD7Of8oiajxXWjHSYPrQVX9EVHcQFKAVpH9q7K9td1pJywKPnk41KrUjju65
